<a href="https://colab.research.google.com/github/HJBJalaly/DLeeg/blob/master/best%20channel/Mine/Search_1Ch_Base_Normal_FitGenerate_4Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
!pip install mne

     |████████████████████████████████| 6.4MB 5.5MB/s 


In [3]:
'''
Rivision:
980726:
  Differenet in/out shift Sampling
980727:
  The model is revised to addapt with fit_generate
  
  

'''

'\nRivision:\n980726:\n  Differenet in/out shift Sampling\n980727:\n  The model is revised to addapt with fit_generate\n  \n  \n\n'

In [0]:
# Parameters:

EpochNum=25
subject_number=109
RemoveBaseLine=0
task_index = [1] # task: REO
Best1Channel=[]
TryStr='Try1'


task_number=1
task_time = 60
sampel_number_per_sec =  160 # sampel rate
total_sampel_number =  sampel_number_per_sec *task_time # 60*160
#sample_shift = 4 #step len
inner_sample_shift = 4 # inner step len
outer_sample_shift =8  # outer step len
window_len= 20
batch_size=64

Search_Space_Channel = [21,23,29,31,33,35,36,40,8,10,12,41,46,48,50,52,54,60,61,62]
Search_Space_Channel_Name=["Fp1","Fp2","F7","F3","Fz","F4","F8","T7","C3","Cz","C4","T8","P7","P3","Pz","P4","P8","O1","Oz","O2"]

# Channel Indexes:
#   Fp1,21
#   Fp2,23
#   F7,29
#   F3,31
#   Fz,33
#   F4,35
#   F8,36
#   T7,40
#   C3,8
#   Cz,10
#   C4,12
#   T8,41
#   P7,46
#   P3,48
#   Pz,50
#   P4,52
#   P8,54
#   O1,60
#   Oz,61
#   O2,62

#   T9,42
#   T10,43


In [5]:
# For Visualization
import matplotlib
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D  # noqa

# General use
import numpy as np
import math
import random

# For clear memory
import gc

#
import copy 
import csv
import pandas as pd
import datetime
import time
import os


# To download file from google drive
from google.colab import files

# For model training
from keras import layers
from keras import models
from keras import regularizers
from keras.utils import to_categorical
from keras import optimizers
from keras import backend as KerasBackend

# EEG Tools
import mne
from mne.preprocessing import create_ecg_epochs, create_eog_epochs
from mne import io
from mne import viz
from mne import Epochs, io, pick_types
from mne.event import define_target_events
from mne.time_frequency import psd_welch
print(__doc__)

Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/numba/decorators.py:146: RuntimeWarning: Caching is not available when the 'parallel' target is in use. Caching is now being disabled to allow execution to continue.
  warnings.warn(msg, RuntimeWarning)


Automatically created module for IPython interactive environment


In [6]:
# load dataset in array

task_number= len(task_index)

# load dataset in array
list_raw_fnames = [[0]*task_number]*subject_number
for x in range(subject_number):
  list_raw_fnames[x] = mne.datasets.eegbci.load_data(x+1,task_index,path='/content/drive/My Drive/Deep Results/Database',update_path=False)

list_rawdata = np.zeros((subject_number,task_number), dtype='object')

for i in range(subject_number):
  for j in range(task_number):
    list_rawdata[i][j] = mne.io.read_raw_edf(list_raw_fnames[i][j], preload=True)



Extracting EDF parameters from /content/drive/My Drive/Deep Results/Database/MNE-eegbci-data/physiobank/database/eegmmidb/S001/S001R01.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 9759  =      0.000 ...    60.994 secs...
Extracting EDF parameters from /content/drive/My Drive/Deep Results/Database/MNE-eegbci-data/physiobank/database/eegmmidb/S002/S002R01.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 9759  =      0.000 ...    60.994 secs...
Extracting EDF parameters from /content/drive/My Drive/Deep Results/Database/MNE-eegbci-data/physiobank/database/eegmmidb/S003/S003R01.edf...
EDF file detected
Setting channel info structure...
Creating raw.info structure...
Reading 0 ... 9759  =      0.000 ...    60.994 secs...
Extracting EDF parameters from /content/drive/My Drive/Deep Results/Database/MNE-eegbci-data/physiobank/database/eegmmidb/S004/S004R01.edf...
EDF file detected


In [7]:
# img for each subject
#subject_img_number = math.floor((total_sampel_number - sampel_number_per_sec) / sample_shift) +1 - window_len +1
subject_img_number = math.floor((total_sampel_number - sampel_number_per_sec - (window_len-1 )*inner_sample_shift) / outer_sample_shift) +1
test_start_index=subject_img_number - math.floor(subject_img_number/4) 

train_number =  test_start_index 
test_number = subject_img_number - test_start_index

subject_number_array_shuffled=np.arange(subject_number)
np.random.shuffle(subject_number_array_shuffled)


subject_img_number_array_shuffled=np.arange(subject_img_number)
np.random.shuffle(subject_img_number_array_shuffled)

print("Train sample:",train_number)
print("Test sample:",test_number)



Train sample: 879
Test sample: 292


In [0]:
def normalize_channel_data(ch , i, ch_min, ch_max):
  ch = ((ch - ch_min[i]) / (ch_max[i] - ch_min[i] ))
  return ch

def ProjectionVector(VecA,VecB):
    Projeted_VecB_on_VecA=np.dot(VecA,VecB)/np.dot(VecA,VecA)*VecA
    return Projeted_VecB_on_VecA
                  

In [0]:
#################################################################################################
## Define Train Data Generator
def GenerateTrainData(BatchSize,ListRawDataMain,SubjectNumberArrayShuffled,ListChannel,RemoveBaseLineFlag,SubjectImgNumberArrayShuffled,WindowLen,OuterSampleShift,InnerSampleShift,SampelNumberPerSec,TestStartIndex):
    
    ch_number=len(ListChannel)
    
    TrainNumber =  TestStartIndex 
    TestNumber = len(SubjectNumberArrayShuffled) - TestStartIndex

    
    Iter=0
    while True:
    
      print('here')
      
      ListRawDataTemp=ListRawDataMain.copy()
      TrainImage=np.zeros((BatchSize, ch_number, WindowLen, 160), dtype = float)
      TrainLabel=np.zeros((BatchSize),dtype=int)
      #Count=0

      # Fill Data Arrays
      for s in SubjectNumberArrayShuffled:

          DataAllChannelsRaw, times =(ListRawDataTemp[s][0][:64,:9600])


          # Extrac Channel T9 or T10 as Baseline
          DataChannelT9Raw =DataAllChannelsRaw[43]# Ch T9 (42) or T10 (43)

          ch_max =[]
          ch_min =[]
          # Extract Selected Channels+ Remove Baseline+ Normailze
          DataChannelsRaw   =np.zeros((ch_number,times.size),dtype = float)
          DataChannelsNormal=np.zeros((ch_number,times.size),dtype = float)
          DataChannelsOrt   =np.zeros((ch_number,times.size),dtype = float)
          for i in range(len(ListChannel)):
              DataChannelsRaw[i]=DataAllChannelsRaw[ListChannel[i]].copy() -DataChannelT9Raw*RemoveBaseLineFlag

              ch_max = np.append(ch_max, max(DataChannelsRaw[i])) # max for each cannel
              ch_min = np.append(ch_min, min(DataChannelsRaw[i])) # min for each cannel

              DataChannelsNormal[i]=normalize_channel_data(DataChannelsRaw[i].copy(), i, ch_min, ch_max)


          # Orthogonal Channel
          DataChannelsOrt[0]=DataChannelsNormal[0]
          #DataChannelsOrt[1]=DataChannelsNormal[1]-ProjectionVector(DataChannelsOrt[0],DataChannelsNormal[1])
          #DataChannelsOrt[2]=DataChannelsNormal[2]-ProjectionVector(DataChannelsOrt[0],DataChannelsNormal[2])\
          #                                        -ProjectionVector(DataChannelsOrt[1],DataChannelsNormal[2])
          #DataChannelsOrt[3]=DataChannelsNormal[3]-ProjectionVector(DataChannelsOrt[0],DataChannelsNormal[3])\
          #                                        -ProjectionVector(DataChannelsOrt[1],DataChannelsNormal[3])\
          #                                        -ProjectionVector(DataChannelsOrt[2],DataChannelsNormal[3])\
          #DataChannelsOrt[4]=DataChannelsNormal[4]-ProjectionVector(DataChannelsOrt[0],DataChannelsNormal[4])\
          #                                        -ProjectionVector(DataChannelsOrt[1],DataChannelsNormal[4])\
          #                                        -ProjectionVector(DataChannelsOrt[2],DataChannelsNormal[4])\
          #                                        -ProjectionVector(DataChannelsOrt[3],DataChannelsNormal[4])\
    
          

          for j in SubjectImgNumberArrayShuffled:
              if j <TestStartIndex :
                  for i in range(len(ListChannel)):
                      for z in range (WindowLen):
                          #ExtractedData=DataChannelsOrt[i,0+(j+z)*sample_shift:sampel_number_per_sec+(j+z)*sample_shift]
                          ExtractedData = DataChannelsOrt[i,0+j*OuterSampleShift + z*InnerSampleShift:SampelNumberPerSec+ j*OuterSampleShift + z*InnerSampleShift]

                          TrainImage[Iter][i][z] = ExtractedData# Data

                  TrainLabel[Iter] = s # label

                  Iter=Iter+1
                  #Count=Count+1
                  if Iter==BatchSize:
                    Iter=0
                    #print('Count=',Count)
                    TrainLabelClass=to_categorical(TrainLabel,len(SubjectNumberArrayShuffled))
                    yield TrainImage   

                

In [0]:
# GenData=GenerateTrainData(BatchSize=32,ListRawDataTemp=list_rawdata.copy(),SubjectNumberArrayShuffled=subject_number_array_shuffled,
#                 ListChannel=[1,2,3,4,5],RemoveBaseLineFlag=0,SubjectImgNumberArrayShuffled=subject_img_number_array_shuffled,WindowLen=window_len,
#                 OuterSampleShift=outer_sample_shift,InnerSampleShift=inner_sample_shift,
#                 SampelNumberPerSec=sampel_number_per_sec,TestStartIndex=test_start_index)
# kk=0
# for i in GenData:
#   print(kk)
#   kk=kk+1
  

In [0]:
#################################################################################################
## Define Test Data Generator
def GenerateTestData(BatchSize,ListRawDataTemp,SubjectNumberArrayShuffled,ListChannel,RemoveBaseLineFlag,SubjectImgNumberArrayShuffled,WindowLen,OuterSampleShift,InnerSampleShift,SampelNumberPerSec,TestStartIndex):
    
    ch_number=len(ListChannel)
    
    TrainNumber =  TestStartIndex 
    TestNumber = len(SubjectNumberArrayShuffled) - TestStartIndex

    TestImage=np.zeros((BatchSize, ch_number, WindowLen, 160), dtype = float)
    TestLabel=np.zeros((BatchSize),dtype=int)
    
    Iter=0
    Count=0
    
    # Fill Data Arrays
    for s in SubjectNumberArrayShuffled:

        DataAllChannelsRaw, times =(ListRawDataTemp[s][0][:64,:9600])


        # Extrac Channel T9 or T10 as Baseline
        DataChannelT9Raw =DataAllChannelsRaw[43]# Ch T9 (42) or T10 (43)

        ch_max =[]
        ch_min =[]
        # Extract Selected Channels+ Remove Baseline+ Normailze
        DataChannelsRaw   =np.zeros((ch_number,times.size),dtype = float)
        DataChannelsNormal=np.zeros((ch_number,times.size),dtype = float)
        DataChannelsOrt   =np.zeros((ch_number,times.size),dtype = float)
        for i in range(len(ListChannel)):
            DataChannelsRaw[i]=DataAllChannelsRaw[ListChannel[i]].copy() -DataChannelT9Raw*RemoveBaseLineFlag
            
            ch_max = np.append(ch_max, max(DataChannelsRaw[i])) # max for each cannel
            ch_min = np.append(ch_min, min(DataChannelsRaw[i])) # min for each cannel
            
            DataChannelsNormal[i]=normalize_channel_data(DataChannelsRaw[i].copy(), i, ch_min, ch_max)

    
        # Orthogonal Channel
        DataChannelsOrt[0]=DataChannelsNormal[0]
        #DataChannelsOrt[1]=DataChannelsNormal[1]-ProjectionVector(DataChannelsOrt[0],DataChannelsNormal[1])
        #DataChannelsOrt[2]=DataChannelsNormal[2]-ProjectionVector(DataChannelsOrt[0],DataChannelsNormal[2])\
        #                                        -ProjectionVector(DataChannelsOrt[1],DataChannelsNormal[2])
        #DataChannelsOrt[3]=DataChannelsNormal[3]-ProjectionVector(DataChannelsOrt[0],DataChannelsNormal[3])\
        #                                        -ProjectionVector(DataChannelsOrt[1],DataChannelsNormal[3])\
        #                                        -ProjectionVector(DataChannelsOrt[2],DataChannelsNormal[3])\
        #DataChannelsOrt[4]=DataChannelsNormal[4]-ProjectionVector(DataChannelsOrt[0],DataChannelsNormal[4])\
        #                                        -ProjectionVector(DataChannelsOrt[1],DataChannelsNormal[4])\
        #                                        -ProjectionVector(DataChannelsOrt[2],DataChannelsNormal[4])\
        #                                        -ProjectionVector(DataChannelsOrt[3],DataChannelsNormal[4])\

    
        #print('here')
        for j in SubjectImgNumberArrayShuffled:
            if j >=TestStartIndex :
                for i in range(len(ListChannel)):
                    for z in range (WindowLen):
                        #ExtractedData=DataChannelsOrt[i,0+(j+z)*sample_shift:sampel_number_per_sec+(j+z)*sample_shift]
                        ExtractedData = DataChannelsOrt[i,0+j*OuterSampleShift + z*InnerSampleShift:SampelNumberPerSec+ j*OuterSampleShift + z*InnerSampleShift]
        
                        TestImage[Iter][i][z] = ExtractedData# Data
                    
                TestLabel[Iter] = s # label
                
                Iter=Iter+1
                Count=Count+1
                if Iter==BatchSize:
                  Iter=0
                  #print('Count=',Count)
                  TestLabelClass=to_categorical(TestLabel,len(SubjectNumberArrayShuffled))
                  yield TestImage,TestLabelClass
                
                

In [82]:
GenTestData = GenerateTestData(BatchSize=1,
                                   ListRawDataTemp=list_rawdata.copy(),
                                   SubjectNumberArrayShuffled=subject_number_array_shuffled,
                                   ListChannel=list_channel,
                                   RemoveBaseLineFlag=RemoveBaseLine,
                                   SubjectImgNumberArrayShuffled=subject_img_number_array_shuffled,
                                   WindowLen=window_len,
                                   OuterSampleShift=outer_sample_shift,
                                   InnerSampleShift=inner_sample_shift,
                                   SampelNumberPerSec=sampel_number_per_sec,
                                   TestStartIndex=test_start_index)
GenTrainDatar=GenerateTrainData(BatchSize=2,
                                   ListRawDataMain=list_rawdata.copy(),
                                   SubjectNumberArrayShuffled=subject_number_array_shuffled,
                                   ListChannel=list_channel,
                                   RemoveBaseLineFlag=RemoveBaseLine,
                                   SubjectImgNumberArrayShuffled=subject_img_number_array_shuffled,
                                   WindowLen=window_len,
                                   OuterSampleShift=outer_sample_shift,
                                   InnerSampleShift=inner_sample_shift,
                                   SampelNumberPerSec=sampel_number_per_sec,
                                   TestStartIndex=test_start_index)

TestResult=model.evaluate_generator(generator=GenTestData,steps=100)
TestResult

[1.1920930376163597e-07, 1.0]

In [112]:
# GenTestData = GenerateTestData(BatchSize=1,
#                                    ListRawDataTemp=list_rawdata.copy(),
#                                    SubjectNumberArrayShuffled=subject_number_array_shuffled,
#                                    ListChannel=list_channel,
#                                    RemoveBaseLineFlag=RemoveBaseLine,
#                                    SubjectImgNumberArrayShuffled=subject_img_number_array_shuffled,
#                                    WindowLen=window_len,
#                                    OuterSampleShift=outer_sample_shift,
#                                    InnerSampleShift=inner_sample_shift,
#                                    SampelNumberPerSec=sampel_number_per_sec,
#                                    TestStartIndex=test_start_index)
# # kk=0
for ii in GenTrainDatar:
  kk=kk+1
  dd,ll=ii
  #print(ll)
  #ii=np.random.rand(2,1,20,160)
  print('k=',kk)
  rr3=model.predict(x=ii)
  print(np.argmax(rr3[0,:]))#,np.argmax(ll[0,:]))
  print(np.argmax(rr3[1,:]))#,np.argmax(ll[1,:]))
#   time.sleep(1)
  break
# rr=model.predict(x=dd)
# print(np.argmax(rr))
# print(np.argmax(ll))


k= 14078
89
89


In [113]:
rr3[0]

array([2.86714268e-19, 4.16403339e-28, 4.23402979e-21, 1.13488453e-20,
       9.35152076e-29, 0.00000000e+00, 5.14036367e-21, 2.69010578e-33,
       1.33341683e-26, 1.71144494e-23, 2.98418391e-38, 1.50872631e-31,
       1.35713569e-33, 5.89992990e-30, 0.00000000e+00, 8.19091072e-27,
       1.36248450e-32, 2.47115889e-35, 8.20681472e-23, 1.36577777e-33,
       4.64499721e-35, 3.08087811e-28, 4.55385865e-32, 4.20056734e-21,
       2.38640738e-30, 1.23724648e-27, 4.12681274e-26, 2.43387060e-33,
       1.20840536e-28, 1.01869789e-28, 3.56197742e-25, 2.22676274e-22,
       1.55324526e-21, 4.01702614e-21, 3.80081710e-31, 1.62374969e-36,
       2.16437926e-21, 1.31000539e-22, 1.72185164e-29, 3.65213611e-35,
       2.57134325e-28, 4.93191832e-26, 7.76310041e-29, 2.53935191e-35,
       5.06629991e-25, 3.99968225e-23, 4.92797023e-33, 1.51567978e-28,
       1.16283692e-32, 5.54141949e-28, 1.28749240e-31, 7.05746583e-23,
       1.09333243e-36, 3.05366913e-31, 1.09435725e-24, 4.65168357e-27,
      

In [80]:
print(np.argmax(pred[0]))
np.argmax(ll[0])

NameError: ignored

In [66]:
history = model.fit_generator(generator=GenTrainData,
                                  epochs =1,
                                  steps_per_epoch=np.ceil(train_number*subject_number/batch_size),
                                  use_multiprocessing=False,
                                  workers=1)
    
    

Epoch 1/1
1498/1498 [==============================] - 13s 9ms/step - loss: 6.7648 - acc: 0.5794


In [62]:
GenData=GenerateTestData(BatchSize=batch_size,ListRawDataTemp=list_rawdata.copy(),SubjectNumberArrayShuffled=subject_number_array_shuffled,
                 ListChannel=[1],RemoveBaseLineFlag=0,SubjectImgNumberArrayShuffled=subject_img_number_array_shuffled,WindowLen=window_len,
                 OuterSampleShift=outer_sample_shift,InnerSampleShift=inner_sample_shift,
                 SampelNumberPerSec=sampel_number_per_sec,TestStartIndex=test_start_index)
kk=0
for i in GenData:
  dd,ll=i
  print(ll)
  print(kk)
  kk=kk+1
  

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
1
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
2
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
3
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
4
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
5
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [

In [12]:
#####################################################################################################
# seacrh all channels


# Read Previous intruppted execution, if any, or create new empty cell
ResultFileName='SearchSpaceResultTable_1Ch_S'+str(subject_number)
if RemoveBaseLine==0:
  ResultFileName=ResultFileName+"_RemoveBaseLineOff"
else:
  ResultFileName=ResultFileName+"_RemoveBaseLineOn"

ResultFileName=ResultFileName+'_SamplesIn'+str(inner_sample_shift)+'Out'+str(outer_sample_shift)+'_'+TryStr+'_'+'.csv'

  
if os.path.isfile('/content/drive/My Drive/Deep Results/'+ResultFileName):
#   print("here")
  SearchSpaceResult=pd.read_csv('/content/drive/My Drive/Deep Results/'+ResultFileName, header=None)
#   print(Test)
  SearchSpaceResult=SearchSpaceResult.values
#   print(Test)
  
else:
    SearchSpaceResult=np.zeros((len(Search_Space_Channel),6),dtype = float)




#####################################################################################################
# seacrh all channels

for IndexCh in range(len(Search_Space_Channel)):
    
    #################################################################################################
    # Print Iteration
    print("#################################################################################################")
    print("Index:", IndexCh," > Channel:", Search_Space_Channel_Name[IndexCh])
    
    if(SearchSpaceResult[IndexCh][0]>0):
      print("  Already Done.")
      continue 
    
    
    #################################################################################################
    # Reset Model and Data Arrays
    list_channel=Best1Channel + [Search_Space_Channel[IndexCh]]
    ch_number=len(list_channel)
    
    list_rawdataTemp=list_rawdata.copy()

    #################################################################################################
    # Construct Data Generator


    GenTrainData=GenerateTrainData(BatchSize=batch_size,
                                   ListRawDataMain=list_rawdata.copy(),
                                   SubjectNumberArrayShuffled=subject_number_array_shuffled,
                                   ListChannel=list_channel,
                                   RemoveBaseLineFlag=RemoveBaseLine,
                                   SubjectImgNumberArrayShuffled=subject_img_number_array_shuffled,
                                   WindowLen=window_len,
                                   OuterSampleShift=outer_sample_shift,
                                   InnerSampleShift=inner_sample_shift,
                                   SampelNumberPerSec=sampel_number_per_sec,
                                   TestStartIndex=test_start_index)

    GenTestData = GenerateTestData(BatchSize=batch_size,
                                   ListRawDataTemp=list_rawdata.copy(),
                                   SubjectNumberArrayShuffled=subject_number_array_shuffled,
                                   ListChannel=list_channel,
                                   RemoveBaseLineFlag=RemoveBaseLine,
                                   SubjectImgNumberArrayShuffled=subject_img_number_array_shuffled,
                                   WindowLen=window_len,
                                   OuterSampleShift=outer_sample_shift,
                                   InnerSampleShift=inner_sample_shift,
                                   SampelNumberPerSec=sampel_number_per_sec,
                                   TestStartIndex=test_start_index)

    #################################################################################################
    # Create Model
    model = models.Sequential()
    model.add(layers.Conv2D(64, (3,3), activation = 'relu', padding='same', input_shape = (ch_number,window_len,160), data_format= "channels_first" ))
    model.add(layers.MaxPooling2D((2,2)))
    model.add(layers.Conv2D(128, (3,3), activation = 'relu'))
    model.add(layers.MaxPooling2D((2,2)))
    model.add(layers.Conv2D(256, (3,3), activation = 'relu'))
    model.add(layers.MaxPooling2D((2,2)))

    model.add(layers.Flatten())
    model.add(layers.Dense(512, activation = 'relu'))
    model.add(layers.Dropout(0.5))
    model.add(layers.Dense(subject_number, activation = 'softmax'))
    
    model.compile(loss= 'categorical_crossentropy',
                  optimizer= optimizers.RMSprop(lr= 1e-4),
                  metrics = ['acc'])
    
    #################################################################################################
    # Train the Model
    history = model.fit_generator(generator=GenTrainData,
                                  epochs =EpochNum,
                                  steps_per_epoch=np.ceil(train_number*subject_number/batch_size),
                                  use_multiprocessing=False,
                                  workers=1)
    
    #################################################################################################
    # Evalute the Model
    TestResult=model.evaluate_generator(GenTestData,steps=np.ceil((subject_img_number-train_number-1)*subject_number/batch_size))
    
    #################################################################################################
    # Extract Result
    SearchSpaceResult[IndexCh][0]=history.history['loss'][EpochNum-1]
    SearchSpaceResult[IndexCh][1]=history.history['acc'][EpochNum-1]
    #SearchSpaceResult[IndexCh][2]=history.history['val_loss'][EpochNum-1]
    #SearchSpaceResult[IndexCh][3]=history.history['val_acc'][EpochNum-1]
    
    SearchSpaceResult[IndexCh][4]=TestResult[0]
    SearchSpaceResult[IndexCh][5]=TestResult[1]
    
    #################################################################################################
    # Save current Result to google drive

    with open('/content/drive/My Drive/Deep Results/'+ResultFileName, 'w+') as csvfile:
      spamwriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
      spamwriter.writerows(SearchSpaceResult)


    #################################################################################################
    # Erase Memory
    KerasBackend.clear_session()
    
    del model
    del history
    del TestResult
    del GenTestData
    del GenTrainData
    
    KerasBackend.clear_session()
    
    time.sleep(2)
    gc.collect()
    time.sleep(2)

    
#################################################################################################    
## Visualize Results and Save Results
Today = datetime.date.today()
TodayStr = Today.strftime("%Y%m%d")
ResultFileName='SearchSpaceResult_1Ch_S'+str(subject_number)
ChannelFileName='ChannelNames_1Ch_S'+str(subject_number)
ImageFileName='SearchSpaceResult_1Ch_S'+str(subject_number)

if RemoveBaseLine==0:
  ResultFileName=ResultFileName+'_RemoveBaseLineOff'
  ChannelFileName=ChannelFileName+'_RemoveBaseLineOff'
  ImageFileName=ImageFileName+'_RemoveBaseLineOff'
else:
  ResultFileName=ResultFileName+'_RemoveBaseLineOn'
  ChannelFileName=ChannelFileName+'_RemoveBaseLineOn'
  ImageFileName=ImageFileName+'_RemoveBaseLineOn'


ResultFileName=ResultFileName+'_SamplesIn'+str(inner_sample_shift)+'Out'+str(outer_sample_shift)+'_'+TryStr+'_'+TodayStr+'.csv'
ChannelFileName=ChannelFileName+'_SamplesIn'+str(inner_sample_shift)+'Out'+str(outer_sample_shift)+'_'+TryStr+'_'+TodayStr+'.csv'
ImageFileName=ImageFileName+'_SamplesIn'+str(inner_sample_shift)+'Out'+str(outer_sample_shift)+'_'+TryStr+'_'+TodayStr+'.pdf'


# Visualize
biosemi_layout = mne.channels.read_layout('biosemi')
biosemi_Acc=copy.deepcopy(biosemi_layout)

for i in range(len(biosemi_Acc.names)):
    biosemi_Acc.names[i]=' '

    
for i in range(len(Search_Space_Channel)):
    index=biosemi_layout.names.index(Search_Space_Channel_Name[i])
    biosemi_Acc.names[index]=biosemi_layout.names[index]+":"+str(np.round(SearchSpaceResult[i][1],3))+\
                                                         ","+str(np.round(SearchSpaceResult[i][5],3))

ImageEEG=biosemi_Acc.plot()
# plt.title("Channel Name : Training Acc.  > Test Acc.",pad=-12)



# Save To Google Drive
ImageEEG.savefig('/content/drive/My Drive/Deep Results/'+ImageFileName)


with open('/content/drive/My Drive/Deep Results/'+ResultFileName, 'w+') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerows(SearchSpaceResult)

with open('/content/drive/My Drive/Deep Results/'+ChannelFileName, 'w+') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerow(Search_Space_Channel)
    spamwriter.writerow(Search_Space_Channel_Name)
    
    
#################################################################################################
# Delete Temp. Result Table File

    

#################################################################################################
Index: 0  > Channel: Fp1
  Already Done.
#################################################################################################
Index: 1  > Channel: Fp2
  Already Done.
#################################################################################################
Index: 2  > Channel: F7
  Already Done.
#################################################################################################
Index: 3  > Channel: F3
  Already Done.
#################################################################################################
Index: 4  > Channel: Fz
  Already Done.
#################################################################################################
Index: 5  > Channel: F4
  Already Done.
#################################################################################################
Index: 6  > Channel: F8
  Already Done.
################################

KeyboardInterrupt: ignored

In [0]:
## Visualize Results and Save Results
Today = datetime.date.today()
TodayStr = Today.strftime("%Y%m%d")
ResultFileName='SearchSpaceResult_1Ch_S'+str(subject_number)
ChannelFileName='ChannelNames_1Ch_S'+str(subject_number)
ImageFileName='SearchSpaceResult_1Ch_S'+str(subject_number)

if RemoveBaseLine==0:
  ResultFileName=ResultFileName+'_RemoveBaseLineOff'
  ChannelFileName=ChannelFileName+'_RemoveBaseLineOff'
  ImageFileName=ImageFileName+'_RemoveBaseLineOff'
else:
  ResultFileName=ResultFileName+'_RemoveBaseLineOn'
  ChannelFileName=ChannelFileName+'_RemoveBaseLineOn'
  ImageFileName=ImageFileName+'_RemoveBaseLineOn'


ResultFileName=ResultFileName+'_SamplesIn'+str(inner_sample_shift)+'Out'+str(outer_sample_shift)+'_'+TryStr+'_'+TodayStr+'.csv'
ChannelFileName=ChannelFileName+'_SamplesIn'+str(inner_sample_shift)+'Out'+str(outer_sample_shift)+'_'+TryStr+'_'+TodayStr+'.csv'
ImageFileName=ImageFileName+'_SamplesIn'+str(inner_sample_shift)+'Out'+str(outer_sample_shift)+'_'+TryStr+'_'+TodayStr+'.pdf'



# Visualize
biosemi_layout = mne.channels.read_layout('biosemi')
biosemi_Acc=copy.deepcopy(biosemi_layout)

for i in range(len(biosemi_Acc.names)):
    biosemi_Acc.names[i]=' '

    
for i in range(len(Search_Space_Channel)):
    index=biosemi_layout.names.index(Search_Space_Channel_Name[i])
    biosemi_Acc.names[index]=biosemi_layout.names[index]+":"+str(np.round(SearchSpaceResult[i][1],3))+\
                                                         ","+str(np.round(SearchSpaceResult[i][5],3))

ImageEEG=biosemi_Acc.plot()
# plt.title("Channel Name : Training Acc.  > Test Acc.",pad=-12)


# Save
ImageEEG.savefig(ImageFileName)

with open(ResultFileName, 'w+') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerows(SearchSpaceResult)

with open(ChannelFileName, 'w+') as csvfile:
    spamwriter = csv.writer(csvfile, delimiter=',',
                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
    spamwriter.writerow(Search_Space_Channel)
    spamwriter.writerow(Search_Space_Channel_Name)
    
# Downlaod
import os
while os.path.isfile(ResultFileName)==False:
  print('wait')
  time.sleep(1)

files.download(ResultFileName)
files.download(ChannelFileName)
files.download(ImageFileName)